{% set version = "1.44.0" %}
{% set name = "grpcio-tools" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be37f458ea510c9a8f1caabbc2b258d12e55d189a567f5edcace90f27dc0efbf
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - grpcio =={{ version }}
    - pip
    - protobuf >=3.6.0
    - python
  run:
    - grpcio =={{ version }}
    - protobuf >=3.6.0
    - python

test:
  imports:
    - grpc_tools

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  doc_source_url: https://github.com/grpc/grpc/tree/master/doc
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - martinRenou
