{% set version = "1.59.2" %}

package:
  name: grpcio-tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grpcio-tools/grpcio-tools-{{ version }}.tar.gz
  sha256: 75905266cf90f1866b322575c2edcd4b36532c33fc512bb1b380dc58d84b1030
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - grpcio {{ ".".join(version.split('.')[:2]) }}
    - pip
    - protobuf >=3.6.0
    - python
  run:
    - setuptools
    - grpcio >=1.59.2
    - protobuf >=4.21.6,<5.0dev
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - grpc_tools

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  doc_source_url: https://github.com/grpc/grpc/tree/master/doc
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - jjerphan
    - martinRenou
    - janjagusch
    - conda-forge/grpc-cpp
