{% set version = "1.58.0" %}

package:
  name: grpcio-tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grpcio-tools/grpcio-tools-{{ version }}.tar.gz
  sha256: 6f4d80ceb591e31ca4dceec747dbe56132e1392a0a9bb1c8fe001d1b5cac898a
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - grpcio =={{ version }}
    - pip
    - protobuf >=3.6.0
    - python
  run:
    - setuptools
    - grpcio >=1.58.0
    - protobuf >=4.21.6,<5.0dev
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - grpc_tools

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  doc_source_url: https://github.com/grpc/grpc/tree/master/doc
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - martinRenou
    - janjagusch
    - conda-forge/grpc-cpp
