{% set version = "1.54.0" %}
{% set name = "grpcio-tools" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df79acbf59997018e131713b716a2fddb5556e1840e9fb9de4ca73bf2059590e
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - grpcio =={{ version }}
    - pip
    - protobuf >=3.6.0
    - python
  run:
    - setuptools
    - grpcio >=1.54.0
    - protobuf >=4.21.6,<5.0dev
    - python

test:
  imports:
    - grpc_tools

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  doc_source_url: https://github.com/grpc/grpc/tree/master/doc
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - martinRenou
    - janjagusch
