{% set version = "1.64.1" %}

package:
  name: grpcio-tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grpcio-tools/grpcio_tools-{{ version }}.tar.gz
  sha256: 72b3550b91adb8354656ecf0f6d1d4611299044bae11fb1e7cc1d1bb66b8c1eb
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

  host:
    - grpcio {{ ".".join(version.split('.')[:2]) }}
    - pip
    - protobuf >=3.6.0
    - python
  run:
    - setuptools
    - grpcio >=1.64.1
    - protobuf <6.0dev,>=5.26.1
    - python

test:
  imports:
    - grpc_tools

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  doc_source_url: https://github.com/grpc/grpc/tree/master/doc
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - JohanMabille
    - jjerphan
    - martinRenou
    - janjagusch
    - conda-forge/grpc-cpp
