{% set name = "grpcio-tools" %}
{% set version = "1.51.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpcio-tools-{{ version }}.tar.gz
  sha256: 8e62d23d3fed9d4f81738f98dd193dbd2e21aed4a8f0dd715e75b5439e649727

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - protobuf >=4.21.6,<5.0dev
    - grpcio >=1.51.1
    - setuptools

test:
  imports:
    - grpc_tools
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  doc_source_url: https://github.com/grpc/grpc/tree/master/doc
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - martinRenou
    - janjagusch
